version: "3.5"

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis_hotel
    # restart: always

    expose:
      - 6379

    networks:
      - hotel

  db:
    image: postgres:13-alpine
    container_name: db_hotel
    # restart: always

    env_file:
      - ./environment/postgresql.env

    environment:
      TZ: "America/Bolivia/La_Paz"

    expose:
      - 5432

    networks:
      - hotel

  gateway:
    image: node:16.5.0-alpine3.12

    volumes:
      - /home/gerardo/Escritorio/Personal  Project/new-moon-hotel/back-end/gateway:/app

    entrypoint: ["/bin/sh", "-c"]

    ports:
      - 443:443

    command:
      - |
        cd /app
        npm run dev

    networks:
      hotel:
        aliases:
          - gateway.hotel

networks:
  hotel:
    name: hotel_new
